class Component < ApplicationRecord
  def self.monster_type_options
    monster_types.keys.map { |k| [ k.titleize, k ] }
  end

  def self.component_type_options
    component_types.keys.map { |k| [ k.titleize, k ] }
  end
  def display_name
    [ monster_type&.to_s&.titleize, component_type&.to_s&.titleize ].compact.join(" ")
  end
  enum :monster_type, {
    aberration: "aberration",
    beast: "beast",
    celestial: "celestial",
    construct: "construct",
    dragon: "dragon",
    elemental: "elemental",
    fey: "fey",
    fiend: "fiend",
    giant: "giant",
    humanoid: "humanoid",
    magical_material: "magical_material",
    monstrosity: "monstrosity",
    ooze: "ooze",
    plant: "plant",
    undead: "undead"
  }, suffix: true

  enum :component_type, {
    antenna: "antenna",
    antler: "antler",
    bark: "bark",
    beak: "beak",
    bone: "bone",
    brain: "brain",
    breath_sac: "breath_sac",
    bundle_of_roots: "bundle_of_roots",
    chitin: "chitin",
    core: "core",
    egg: "egg",
    ethereal_ichor: "ethereal_ichor",
    eye: "eye",
    fat: "fat",
    fin: "fin",
    flesh: "flesh",
    gears: "gears",
    heart: "heart",
    hide: "hide",
    horn: "horn",
    instructions: "instructions",
    lifespark: "lifespark",
    liver: "liver",
    main_eye: "main_eye",
    marrow: "marrow",
    membrane: "membrane",
    nail: "nail",
    phial_of_acid: "phial_of_acid",
    phial_of_blood: "phial_of_blood",
    phial_of_congealed_blood: "phial_of_congealed_blood",
    phial_of_mucus: "phial_of_mucus",
    phial_of_oil: "phial_of_oil",
    phial_of_sap: "phial_of_sap",
    phial_of_wax: "phial_of_wax",
    pelt: "pelt",
    pincer: "pincer",
    skin: "skin",
    rancid_fat: "rancid_fat",
    undying_flesh: "undying_flesh",
    undying_heart: "undying_heart",
    plating: "plating",
    poison_gland: "poison_gland",
    pouch_of_claws: "pouch_of_claws",
    pouch_of_dust: "pouch_of_dust",
    pouch_of_feathers: "pouch_of_feathers",
    pouch_of_hyphae: "pouch_of_hyphae",
    pouch_of_leaves: "pouch_of_leaves",
    pouch_of_pollen: "pouch_of_pollen",
    pouch_of_scales: "pouch_of_scales",
    pouch_of_spores: "pouch_of_spores",
    pouch_of_teeth: "pouch_of_teeth",
    primordial_dust: "primordial_dust",
    psyche: "psyche",
    soul: "soul",
    stinger: "stinger",
    stone: "stone",
    talon: "talon",
    tentacle: "tentacle",
    tooth: "tooth",
    tongue: "tongue",
    tuber: "tuber",
    tusk: "tusk",
    undying_flesh: "undying_flesh",
    undying_heart: "undying_heart",
    vesicle: "vesicle",
    volatile_mote: "volatile_mote",
    blood_mithral: "blood_mithral",
    subeye: "subeye",
    volatile_mote_of_air: "volatile_mote_of_air",
    volatile_mote_of_earth: "volatile_mote_of_earth",
    volatile_mote_of_fire: "volatile_mote_of_fire",
    volatile_mote_of_water: "volatile_mote_of_water",
    volatile_mote_of_tar: "volatile_mote_of_tar",
    core_of_air: "core_of_air",
    core_of_earth: "core_of_earth",
    core_of_fire: "core_of_fire",
    core_of_water: "core_of_water",
    core_of_tar: "core_of_tar"
  }, suffix: true
end
